/**
 * Generator orchestration.
 *
 * Parses TL schemas and generates all TypeScript output files
 * (types, constructor IDs, serializer registry).
 */

export { crc32 } from './crc32.js';
export { generateTypeScript } from './typescript.js';
export { generateSerializerRegistry } from './serializer.js';

import { parseTLSchema } from '../parser/parser.js';
import { generateTypeScript } from './typescript.js';
import { generateSerializerRegistry } from './serializer.js';
import type { TLSchema } from '../parser/types.js';

/**
 * Merge two TL schemas. Constructors and functions from the second
 * schema are appended to those from the first.
 */
export function mergeSchemas(a: TLSchema, b: TLSchema): TLSchema {
  return {
    constructors: [...a.constructors, ...b.constructors],
    functions: [...a.functions, ...b.functions],
    layer: a.layer || b.layer,
  };
}

/**
 * Result of code generation — a map of relative file paths → content.
 */
export interface GeneratedFiles {
  'types.ts': string;
  'constructorIds.ts': string;
  'registry.ts': string;
  'index.ts': string;
}

/**
 * Generate all output files from raw TL schema strings.
 *
 * @param apiTL - Contents of api.tl
 * @param mtprotoTL - Contents of mtproto.tl
 * @returns Map of file names to generated code
 */
export function generateAll(apiTL: string, mtprotoTL: string): GeneratedFiles {
  const apiSchema = parseTLSchema(apiTL);
  const mtprotoSchema = parseTLSchema(mtprotoTL);
  const merged = mergeSchemas(apiSchema, mtprotoSchema);

  const { types, constructorIds } = generateTypeScript(merged);
  const registry = generateSerializerRegistry(merged);

  const indexTs = [
    '// Auto-generated by @mtproto2/tl-schema. DO NOT EDIT.',
    '',
    "export * from './types.js';",
    "export { constructorIds, constructorNames } from './constructorIds.js';",
    "export { registry, registryByName } from './registry.js';",
    "export type { FieldDescriptor, ConstructorDescriptor } from './registry.js';",
    '',
  ].join('\n');

  return {
    'types.ts': types,
    'constructorIds.ts': constructorIds,
    'registry.ts': registry,
    'index.ts': indexTs,
  };
}
