/**
 * Serializer/deserializer registry generator.
 *
 * Generates a registry mapping constructor IDs to encode/decode
 * function descriptors. These are consumed by the binary package
 * to perform actual TL serialization.
 */

import type { TLConstructor, TLSchema } from '../parser/types.js';

/** Describes how to encode/decode a single field. */
interface FieldDescriptor {
  name: string;
  type: string;
  isFlag: boolean;
  flagField: string | null;
  flagIndex: number | null;
  isTrueFlag: boolean;
  isVector: boolean;
  innerType: string | null;
}

/**
 * Map a TL type to a serialization method name.
 */
function serMethodForType(type: string): string {
  switch (type) {
    case 'int':
    case '#':
      return 'Int32';
    case 'long':
      return 'Int64';
    case 'double':
      return 'Double';
    case 'int128':
      return 'Int128';
    case 'int256':
      return 'Int256';
    case 'string':
      return 'String';
    case 'bytes':
      return 'Bytes';
    case 'Bool':
      return 'Bool';
    case 'true':
      return 'True';
    case 'Object':
    case '!X':
    case 'X':
      return 'Object';
    default:
      return 'TLObject';
  }
}

/**
 * Generate the serializer registry code.
 *
 * This creates a registry.ts file with encode/decode descriptors for all
 * constructors and functions.
 */
export function generateSerializerRegistry(schema: TLSchema): string {
  const allConstructors = [...schema.constructors, ...schema.functions];

  const lines: string[] = [];
  lines.push('// Auto-generated by @mtproto2/tl-schema. DO NOT EDIT.');
  lines.push('// eslint-disable-next-line @typescript-eslint/ban-ts-comment');
  lines.push('// @ts-nocheck');
  lines.push('');
  lines.push('/**');
  lines.push(' * Field descriptor for serialization/deserialization.');
  lines.push(' */');
  lines.push('export interface FieldDescriptor {');
  lines.push('  name: string;');
  lines.push('  type: string;');
  lines.push('  method: string;');
  lines.push('  isFlag: boolean;');
  lines.push('  flagField: string | null;');
  lines.push('  flagIndex: number | null;');
  lines.push('  isTrueFlag: boolean;');
  lines.push('  isVector: boolean;');
  lines.push('  innerType: string | null;');
  lines.push('  innerMethod: string | null;');
  lines.push('}');
  lines.push('');
  lines.push('/**');
  lines.push(' * Constructor descriptor in the registry.');
  lines.push(' */');
  lines.push('export interface ConstructorDescriptor {');
  lines.push('  id: number;');
  lines.push('  name: string;');
  lines.push('  isFunction: boolean;');
  lines.push('  fields: FieldDescriptor[];');
  lines.push('}');
  lines.push('');
  lines.push('/** Registry of all TL constructors, keyed by constructor ID. */');
  lines.push('export const registry: Map<number, ConstructorDescriptor> = new Map();');
  lines.push('');
  lines.push('/** Reverse lookup: constructor name → descriptor. */');
  lines.push('export const registryByName: Map<string, ConstructorDescriptor> = new Map();');
  lines.push('');

  // Generate registration calls
  for (const ctor of allConstructors) {
    const hex = '0x' + ctor.id.toString(16).padStart(8, '0');
    lines.push(`{`);
    lines.push(`  const desc: ConstructorDescriptor = {`);
    lines.push(`    id: ${hex},`);
    lines.push(`    name: '${ctor.name}',`);
    lines.push(`    isFunction: ${ctor.isFunction},`);
    lines.push(`    fields: [`);

    for (const param of ctor.params) {
      const method = serMethodForType(param.type);
      const innerMethod = param.isVector && param.innerType
        ? serMethodForType(param.innerType)
        : null;

      lines.push(`      {`);
      lines.push(`        name: '${param.name}',`);
      lines.push(`        type: '${param.type}',`);
      lines.push(`        method: '${method}',`);
      lines.push(`        isFlag: ${param.isFlag},`);
      lines.push(`        flagField: ${param.flagField ? `'${param.flagField}'` : 'null'},`);
      lines.push(`        flagIndex: ${param.flagIndex ?? 'null'},`);
      lines.push(`        isTrueFlag: ${param.isTrueFlag},`);
      lines.push(`        isVector: ${param.isVector},`);
      lines.push(`        innerType: ${param.innerType ? `'${param.innerType}'` : 'null'},`);
      lines.push(`        innerMethod: ${innerMethod ? `'${innerMethod}'` : 'null'},`);
      lines.push(`      },`);
    }

    lines.push(`    ],`);
    lines.push(`  };`);
    lines.push(`  registry.set(${hex}, desc);`);
    lines.push(`  registryByName.set('${ctor.name}', desc);`);
    lines.push(`}`);
    lines.push('');
  }

  return lines.join('\n');
}
