/**
 * TypeScript type generator.
 *
 * Takes a parsed TLSchema AST and generates TypeScript interfaces,
 * union types, and a constructor ID map.
 */

import type { TLConstructor, TLSchema } from '../parser/types.js';

/** Map TL type names to TypeScript type names. */
function tlTypeToTs(tlType: string): string {
  switch (tlType) {
    case 'int':
    case 'double':
      return 'number';
    case 'long':
      return 'bigint';
    case 'int128':
      return 'Uint8Array';
    case 'int256':
      return 'Uint8Array';
    case 'string':
      return 'string';
    case 'bytes':
      return 'Uint8Array';
    case 'Bool':
    case 'true':
      return 'boolean';
    case '#':
      return 'number';
    case 'Object':
    case '!X':
    case 'X':
      return 'unknown';
    default:
      // Reference to another generated type
      return `TL${sanitizeTypeName(tlType)}`;
  }
}

/**
 * Sanitize a TL type name into a valid TypeScript identifier.
 * E.g. "messages.Chats" → "MessagesChats", "InputPeer" → "InputPeer"
 */
function sanitizeTypeName(name: string): string {
  return name
    .split('.')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Sanitize a TL constructor name into a valid TypeScript interface name.
 * E.g. "messages.sentMessage" → "MessagesSentMessage"
 * E.g. "boolFalse" → "BoolFalse"
 */
function constructorToInterfaceName(name: string): string {
  return (
    'TL' +
    name
      .split('.')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
  );
}

/**
 * Convert a parameter name to a safe TypeScript property name.
 * Escapes reserved words if needed.
 */
function safeParamName(name: string): string {
  const reserved = new Set([
    'delete', 'default', 'export', 'import', 'return', 'class', 'switch',
    'case', 'break', 'continue', 'new', 'typeof', 'instanceof', 'void',
    'function', 'var', 'let', 'const', 'enum', 'interface', 'type',
    'extends', 'implements', 'static', 'public', 'private', 'protected',
    'abstract', 'yield', 'package', 'in', 'of',
  ]);
  if (reserved.has(name)) {
    return `${name}_`;
  }
  return name;
}

/**
 * Generate the TypeScript type string for a constructor parameter.
 */
function paramTypeToTs(param: { type: string; isVector: boolean; innerType: string | null; isTrueFlag: boolean }): string {
  if (param.isTrueFlag) {
    return 'true';
  }
  if (param.isVector) {
    const inner = tlTypeToTs(param.innerType ?? 'unknown');
    return `Array<${inner}>`;
  }
  return tlTypeToTs(param.type);
}

/**
 * Generate TypeScript code for a parsed TL schema.
 *
 * Returns an object containing all generated code strings.
 */
export function generateTypeScript(schema: TLSchema): {
  types: string;
  constructorIds: string;
} {
  const allConstructors = [...schema.constructors, ...schema.functions];

  // Group constructors by result type to build union types
  const typeToConstructors = new Map<string, TLConstructor[]>();
  for (const ctor of allConstructors) {
    const existing = typeToConstructors.get(ctor.type) ?? [];
    existing.push(ctor);
    typeToConstructors.set(ctor.type, existing);
  }

  const lines: string[] = [];
  lines.push('// Auto-generated by @kerainmtp/tl-schema. DO NOT EDIT.');
  lines.push('// eslint-disable-next-line @typescript-eslint/ban-ts-comment');
  lines.push('// @ts-nocheck');
  lines.push('');

  // Generate interfaces for each constructor
  for (const ctor of allConstructors) {
    const interfaceName = constructorToInterfaceName(ctor.name);
    lines.push(`export interface ${interfaceName} {`);
    lines.push(`  _: '${ctor.name}';`);

    for (const param of ctor.params) {
      // Skip the flags bitfield from the TS interface — it is only used internally
      // Actually, keep it in case callers need to construct raw objects
      const tsType = paramTypeToTs(param);
      const propName = safeParamName(param.name);
      const optional = param.isFlag ? '?' : '';
      lines.push(`  ${propName}${optional}: ${tsType};`);
    }

    lines.push('}');
    lines.push('');
  }

  // Generate union types for result types that have multiple constructors
  const generatedUnions = new Set<string>();
  for (const [resultType, ctors] of typeToConstructors) {
    // Skip generic types like "X"
    if (resultType === 'X' || resultType === '!X') continue;

    const unionName = `TL${sanitizeTypeName(resultType)}`;
    // If a union name collides with a single constructor interface name, skip
    // (this happens when there's exactly one constructor for a type)
    if (ctors.length === 1) {
      const singleInterfaceName = constructorToInterfaceName(ctors[0].name);
      if (unionName === singleInterfaceName) continue;
    }
    if (generatedUnions.has(unionName)) continue;
    generatedUnions.add(unionName);

    const members = ctors.map((c) => constructorToInterfaceName(c.name));
    if (members.length === 1) {
      lines.push(`export type ${unionName} = ${members[0]};`);
    } else {
      lines.push(`export type ${unionName} =`);
      for (let i = 0; i < members.length; i++) {
        const sep = i < members.length - 1 ? '' : ';';
        lines.push(`  | ${members[i]}${sep}`);
      }
    }
    lines.push('');
  }

  // Generate constructor name literal type union
  lines.push('/** All known constructor names. */');
  lines.push('export type TLConstructorName =');
  for (let i = 0; i < allConstructors.length; i++) {
    const sep = i < allConstructors.length - 1 ? '' : ';';
    lines.push(`  | '${allConstructors[i].name}'${sep}`);
  }
  lines.push('');

  // Generate the TLObject union (all constructor interfaces)
  lines.push('/** Union of all TL object types. */');
  lines.push('export type TLObject =');
  for (let i = 0; i < allConstructors.length; i++) {
    const sep = i < allConstructors.length - 1 ? '' : ';';
    lines.push(`  | ${constructorToInterfaceName(allConstructors[i].name)}${sep}`);
  }
  lines.push('');

  const typesCode = lines.join('\n');

  // Generate constructor ID map
  const idLines: string[] = [];
  idLines.push('// Auto-generated by @kerainmtp/tl-schema. DO NOT EDIT.');
  idLines.push('');
  idLines.push('/** Map of constructor ID (number) to constructor name. */');
  idLines.push('export const constructorIds: Record<number, string> = {');
  for (const ctor of allConstructors) {
    const hex = '0x' + ctor.id.toString(16).padStart(8, '0');
    idLines.push(`  ${hex}: '${ctor.name}',`);
  }
  idLines.push('};');
  idLines.push('');

  idLines.push('/** Map of constructor name to constructor ID. */');
  idLines.push('export const constructorNames: Record<string, number> = {');
  for (const ctor of allConstructors) {
    const hex = '0x' + ctor.id.toString(16).padStart(8, '0');
    idLines.push(`  '${ctor.name}': ${hex},`);
  }
  idLines.push('};');
  idLines.push('');

  const constructorIdsCode = idLines.join('\n');

  return {
    types: typesCode,
    constructorIds: constructorIdsCode,
  };
}
